config/routes.rb
Rails.application.routes.draw do
	
  resources :invoice_items
  resources :clients
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	#belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	#has_many :invoice_items, :dependent => :destroy
	#has_one :client, foreign_key: "company"

	serialize :invoice_items, Hash
	#accepts_nested_attributes_for :invoice_items
    #accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to edit_client_path(@client), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to edit_client_path(@client), notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:contact_name, :company, :email, :fax, :phone, :cell, :website, :address, :address_2, :city, :state, :zip)
    end
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :set_invoice_item, only: [:show, :edit, :update, :destroy]

  # GET /invoice_items
  # GET /invoice_items.json
  def index
    @invoice_items = InvoiceItem.all
  end

  # GET /invoice_items/1
  # GET /invoice_items/1.json
  def show
  end

  # GET /invoice_items/new
  def new
    @invoice_item = InvoiceItem.new
  end

  # GET /invoice_items/1/edit
  def edit
  end

  # POST /invoice_items
  # POST /invoice_items.json
  def create
    invoice = Invoice.find(params:[:invoice_id])
    @invoice_item = invoice_items.build(invoice: invoice)#InvoiceItem.new(invoice_item_params)

    respond_to do |format|
      if @invoice_item.save
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_item }
      else
        format.html { render :new }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_items/1
  # PATCH/PUT /invoice_items/1.json
  def update
    respond_to do |format|
      if @invoice_item.update(invoice_item_params)
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_items/1
  # DELETE /invoice_items/1.json
  def destroy
    @invoice_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_items_url, notice: 'Invoice item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_item
      @invoice_item = InvoiceItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_item_params
      params.require(:invoice_item).permit(:invoice_id, :invoice_id)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show

    #to_s(@invoice)

    #@invoice = Invoice.find(params[:id]) #(params[:id])

    @client = Client.where(company: "#{@invoice.client}").take

    #find_by_sql("SELECT * FROM clients WHERE company = 'plow'")

    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "#{@invoice.client}-invoice-#{@invoice.invoice_number}",
            page_size: 'A4',
            template: "invoices/show.html.erb",
            layout: "pdf.html",
            orientation: "Portrait",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
    end

  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    @in = Invoice.all.maximum("invoice_number")
    
    if @in.to_s.empty?
      @invoice.invoice_number = 1
    else 
      @invoice.invoice_number = @in.to_i + 1
    end

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to edit_invoice_path(@invoice), notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update

    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to edit_invoice_path(@invoice), notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])

      @clients = Client.find_by_sql("SELECT * FROM clients")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_number, :project_title, :client, :issue_date, :due_date, :description, :status, :notes, :terms, :item_description, :item_qty, :item_rate, :item_amount, :subtotal, :tax_total, :items_total, :invoice_items => [:description, :qty, :rate, :total])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
<div class="row gtr-uniform ">

  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :contact_name, placeholder: "Contact Name" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :company, placeholder: "Company" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :email, placeholder: "Email" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :fax, placeholder: "Fax" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :phone, placeholder: "Phone" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :cell, placeholder: "Cell" %>
  </div>

  <div class="field col-9 col-12-xsmall">
    <%= f.text_field :website, placeholder: "Website" %>
  </div>

  <div class="field col-9 col-12-xsmall">
    <%= f.text_field :address, placeholder: "Address" %>
  </div>

  <div class="field col-9 col-12-xsmall">
    <%= f.text_field :address_2, placeholder: "Address 2" %>
  </div>

  <div class="field col-4 col-12-xsmall">
    <%= f.text_field :city, placeholder: "City" %>
  </div>

  <div class="field col-4 col-12-xsmall">
    <%= f.text_field :state, placeholder: "State" %>
  </div>

  <div class="field col-4 col-12-xsmall">
    <%= f.text_field :zip, placeholder: "Zip" %>
  </div>

  <div class="field col-4 col-12-xsmall">
    <%= f.text_field :address_2, placeholder: "Rate" %>
  </div>

  <div class="actions col-12 col-12-xsmall">
    <%= f.submit %>
  </div>

</div>
<% end %>

app/views/clients/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Edit Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %> |
<%= link_to 'View', @client %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>All Clients <span><%= link_to 'ADD NEW', new_client_path, class: 'button small' %></span></h1>-->


<div class="row">
  <div class="col-10"><h1>All Clients</h1></div>
  <div class="col-2"><%= link_to 'ADD NEW', new_client_path, class: 'button small' %></div>
</div>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.company, edit_client_path(client) %></td>
        <td><%= client.contact_name %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <!--<td><%= client.cell %></td>
        <td><%= client.website %></td>
        <td><%= client.address %></td>
        <td><%= client.address_2 %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>-->
        <!--<td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>-->
        <td><%= link_to '', client, method: :delete, class: 'fa fa-minus-circle', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact name:</strong>
  <%= @client.contact_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @client.fax %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @client.cell %>
</p>

<p>
  <strong>Website:</strong>
  <%= @client.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @client.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/invoice_items/_form.html.erb
<%= form_for(invoice_item) do |f| %>
  <% if invoice_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_item.errors.count, "error") %> prohibited this invoice_item from being saved:</h2>

      <ul>
      <% invoice_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_id %>
    <%= f.text_field :invoice_id %>
  </div>

  <div class="field">
    <%= f.label :invoice_id %>
    <%= f.text_field :invoice_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoice_items/edit.html.erb
<h1>Editing Invoice Item</h1>

<%= render 'form', invoice_item: @invoice_item %>

<%= link_to 'Show', @invoice_item %> |
<%= link_to 'Back', invoice_items_path %>

app/views/invoice_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Items</h1>

<table>
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_items.each do |invoice_item| %>
      <tr>
        <td><%= invoice_item.invoice %></td>
        <td><%= invoice_item.invoice %></td>
        <td><%= link_to 'Show', invoice_item %></td>
        <td><%= link_to 'Edit', edit_invoice_item_path(invoice_item) %></td>
        <td><%= link_to 'Destroy', invoice_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Item', new_invoice_item_path %>

app/views/invoice_items/new.html.erb
<h1>New Invoice Item</h1>

<%= render 'form', invoice_item: @invoice_item %>

<%= link_to 'Back', invoice_items_path %>

app/views/invoice_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_item.invoice %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_item.invoice %>
</p>

<%= link_to 'Edit', edit_invoice_item_path(@invoice_item) %> |
<%= link_to 'Back', invoice_items_path %>

app/views/invoices/_form.html.erb
<%= form_for(invoice) do |f| %>
<h3>Details</h3>
<div class="row gtr-uniform ">
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%#= @clients.inspect %>
  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :project_title, placeholder: "Project Title" %>
  </div>

  <div class="field col-6 col-12-xsmall">

    <%= select_tag ":client", options_for_select(@clients.map  { |value| [value["company"], value["company"]] }) %>
   
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :issue_date %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.text_field :due_date %>
  </div>

  <div class="field col-7 col-12-xsmall">
    <%= f.text_area :description, placeholder: "Brief Description" %>
  </div>

  <div class="field col-6 col-12-xsmall">
    <%= f.select :status, ['', 'Paid', 'Sent', 'Overdue'] %>
  </div>

  <div class="field col-12 col-12-xsmall">
    <%= f.text_area :notes, placeholder: "Notes" %>
  </div>

  <div class="field col-12 col-12-xsmall">
    <%= f.text_area :terms, placeholder: "Terms" %>
  </div>

  <div class="col-12 col-12-xsmall">

        <div class="table-wrapper">
          <h3>Items</h3>
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Rate</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>

                <% if @invoice.invoice_items %>
                  <% @invoice.invoice_items.each_pair do |key, value| %>
                     <tr id="clonedInput-<%= key %>" class="clonedInput invoice-line-item">
                     <td><button type="button" class="remove"><span class="fa fa-minus-circle"></span></button></td>
                      <td>
                        <input 
                        class="line-item-description" 
                        multiple="multiple" 
                        type="text" 
                        name="invoice[invoice_items][<%= key %>][description]" 
                        id="invoice_invoice_items_description" value="<%= value["description"] %>">
                      </td>

                      <td>
                        <input 
                        class="numeric line-item-qty" 
                        multiple="multiple" 
                        type="text" 
                        name="invoice[invoice_items][<%= key %>][qty]" 
                        id="invoice_invoice_items_qty" value="<%= value["qty"] %>">
                      </td>

                      <td>
                        <input 
                        class="line-item-rate numeric"
                         multiple="multiple" 
                         type="text" 
                         name="invoice[invoice_items][<%= key %>][rate]" 
                         id="invoice_invoice_items_rate" value="<%= value["rate"] %>">
                      </td>

                      <td>
                        <input 
                        class="price line-item-total" 
                        multiple="multiple" 
                        type="text" 
                        name="invoice[invoice_items][<%= key %>][total]" 
                        id="invoice_invoice_items_total" value="<%= value["total"] %>">
                      </td>
                    </tr> 
                  <% end %>
                <% else %>
                <tr id="clonedInput-0" class="clonedInput invoice-line-item">
                                       <td><button type="button" class="remove"><span class="fa fa-minus-circle"></span></button></td>

                  <td><input class="line-item-description" multiple="multiple" type="text" name="invoice[invoice_items][0][description]" id="invoice_invoice_items_description"></td>
                  <td><input class="numeric line-item-qty" multiple="multiple" type="text" name="invoice[invoice_items][0][qty]" id="invoice_invoice_items_qty"></td>
                  <td><input class="line-item-rate numeric" multiple="multiple" type="text" name="invoice[invoice_items][0][rate]" id="invoice_invoice_items_rate"></td>
                  <td><input class="price line-item-total" multipl.e="multiple" type="text" name="invoice[invoice_items][0][total]" id="invoice_invoice_items_total"></td>
                </tr>
                <% end %>
              
              
            </tbody>
            <tfoot>
              <tr>
                <td colspan="4"></td>
                <td><button class="button primary fit clone" type="button">Add New</button></td>
              </tr>
              <tr>
                <td colspan="3"></td>
                <td>Sub Total:</td>
                <td><%= f.text_field :subtotal, class: 'disabled line-items-sub-total' %></td>
              </tr>
              <tr>
                <td colspan="3"></td>
                <td>Tax Total:(<span class="invoice-tax-rate">0</span>%)</td>
                <td><%= f.text_field :tax_total, class: 'disabled line-items-tax-total' %></td>
              </tr>
              <tr>
                <td colspan="3"></td>
                <td>Total:</td>
                <td><%= f.text_field :items_total, class: 'disabled line-items-total' %></td>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

<script>
$(document).ready(function() {

    /* custom */
    //$('.date-picker').datepicker();

      var last_css_id_array = $(".clonedInput").last().attr('id').slice('-');
      var row_key = last_css_id_array[last_css_id_array.length - 1];

      function clone(e){
        e.preventDefault;

          row_key++;

          /*var header_row_template =
          '<tr id="clonedInput-' + row_key + '" class="clonedInput invoice-line-item">' +
        '<td><button type="button" class="remove"><span class="fa fa-minus-circle"></span></button></td>' +
        '<td><input type="text" name="line-item[' + row_key + '][description]" id="line-item-description" class="large-text" value=""></td>' +
      '<td><input type="text" name="line-item[' + row_key + '][qty]" id="line-item-qty" class="large-text numeric line-item-qty" value=""></td>' +
      '<td><input type="text" size="4" name="line-item[' + row_key + '][rate]" id="line-item-rate" class="line-item-rate numeric" value=""></td>' +
      '<td><input type="text" size="6" name="line-item[' + row_key + '][total]" id="line-item-total" class="price line-item-total" value=""></td>' +
      '</tr>';*/
          var header_row_template =
          '<tr id="clonedInput-' + row_key + '" class="clonedInput invoice-line-item">' +
          '<td><button type="button" class="remove"><span class="fa fa-minus-circle"></span></button></td>' +
          '<td><input type="text" name="invoice[invoice_items][' + row_key + '][description]" id="line-item-description" class="large-text" value=""></td>' +
          '<td><input type="text" name="invoice[invoice_items][' + row_key + '][qty]" id="line-item-qty" class="large-text numeric line-item-qty" value=""></td>' +
          '<td><input type="text" size="4" name="invoice[invoice_items][' + row_key + '][rate]" id="line-item-rate" class="line-item-rate numeric" value=""></td>' +
          '<td><input type="text" size="6" name="invoice[invoice_items][' + row_key + '][total]" id="line-item-total" class="price line-item-total" value=""></td>' +
          '</tr>';

          $('.clonedInput').last().after(header_row_template);

      }

      function remove(){
          var cloneCount = $(".clonedInput").length;
          if(cloneCount > 1) {
              $(this).parents(".clonedInput").remove();
          }

      //update totals
      update_total();
      }

      $("body").delegate(".clone","click", clone);
      $("body").delegate("button.remove","click", remove);

    function roundNumber(number,decimals) {
      var newString;// The new rounded number
      decimals = Number(decimals);
      if (decimals < 1) {
        newString = (Math.round(number)).toString();
      } else {
        var numString = number.toString();
        if (numString.lastIndexOf(".") == -1) {// If there is no decimal point
          numString += ".";// give it one at the end
        }
        var cutoff = numString.lastIndexOf(".") + decimals;// The point at which to truncate the number
        var d1 = Number(numString.substring(cutoff,cutoff+1));// The value of the last decimal place that we'll end up with
        var d2 = Number(numString.substring(cutoff+1,cutoff+2));// The next decimal, after the last one we want
        if (d2 >= 5) {// Do we need to round up at all? If not, the string will just be truncated
          if (d1 == 9 && cutoff > 0) {// If the last digit is 9, find a new cutoff point
            while (cutoff > 0 && (d1 == 9 || isNaN(d1))) {
              if (d1 != ".") {
                cutoff -= 1;
                d1 = Number(numString.substring(cutoff,cutoff+1));
              } else {
                cutoff -= 1;
              }
            }
          }
          d1 += 1;
        }
        if (d1 == 10) {
          numString = numString.substring(0, numString.lastIndexOf("."));
          var roundedNum = Number(numString) + 1;
          newString = roundedNum.toString() + '.';
        } else {
          newString = numString.substring(0,cutoff) + d1.toString();
        }
      }
      if (newString.lastIndexOf(".") == -1) {// Do this again, to the new string
        newString += ".";
      }
      var decs = (newString.substring(newString.lastIndexOf(".")+1)).length;
      for(var i=0;i<decimals-decs;i++) newString += "0";
      //var newNumber = Number(newString);// make it a number if you like
      return newString; // Output the result to the form field (change for your purposes)
    }


    function calculate_tax() {
      //get tax rate (.12)
      var taxRate = parseFloat( $('.invoice-tax-rate').text() ) / 100;

      //tax total (sub total box * user set tax [converted to decimal])
      var taxTotal = parseFloat( $('.line-items-sub-total').val() ) * taxRate;

      //update tax total box
      $('.line-items-tax-total').val(taxTotal.toFixed(2));

      //update invoice total
      var invoiceTotal = parseFloat( $('.line-items-sub-total').val() ) + parseFloat( $('.line-items-tax-total').val() );

      $('.line-items-total').val(invoiceTotal.toFixed(2));

    }

    function update_total() {

      var sum = 0.00;
      $('.price').each(function() {
        if ( $(this).val() != ''){
           sum += parseFloat($(this).val());
        }
      });

      $('.line-items-sub-total').val(sum.toFixed(2));

      calculate_tax();

    }

    function update_price() {
          //get main block from clicked item
      var row = $(this).parents('.clonedInput');
          var price = row.find('.line-item-qty').val() * row.find('.line-item-rate').val();

      //price = price, 2;
      row.find('input.price').val(price.toFixed(2));

      update_total();
    }

    $("body").delegate(".line-item-rate","blur", update_price);
    $("body").delegate(".line-item-qty","blur", update_price);
})

</script>

app/views/invoices/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Edit Invoice <span># <%= @invoice.invoice_number %></span></h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %> | <%= link_to 'View', invoice_path(@invoice, format: :pdf) %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Due</th>
      <th>Project</th>
      <th>Client</th>
      <th>Status</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.invoice_number, edit_invoice_path(invoice) %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.project_title %></td>
        <td><%= invoice.client %></td>
        <td><%= invoice.status or "active" %></td>

        <td><%= invoice.items_total %></td>
        <!--<td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>-->
        <td><%= link_to '', invoice, method: :delete, class: 'fa fa-minus-circle',  data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>